package com.iamnaran.firefly.ui.theme

import androidx.compose.ui.graphics.Color



val appLightPrimary = Color(0xFF825500)
val appLightOnPrimary = Color(0xFFFFFFFF)
val appLightPrimaryContainer = Color(0xFFFFDDAE)
val appLightOnPrimaryContainer = Color(0xFF2A1800)
val appLightSecondary = Color(0xFF6F5B40)
val appLightOnSecondary = Color(0xFFFFFFFF)
val appLightSecondaryContainer = Color(0xFFFADEBC)
val appLightOnSecondaryContainer = Color(0xFF271904)
val appLightTertiary = Color(0xFF516440)
val appLightOnTertiary = Color(0xFFFFFFFF)
val appLightTertiaryContainer = Color(0xFFD3EABC)
val appLightOnTertiaryContainer = Color(0xFF102004)
val appLightError = Color(0xFFBA1B1B)
val appLightErrorContainer = Color(0xFFFFDAD4)
val appLightOnError = Color(0xFFFFFFFF)
val appLightOnErrorContainer = Color(0xFF410001)
val appLightBackground = Color(0xFFFCFCFC)
val appLightOnBackground = Color(0xFF1F1B16)
val appLightSurface = Color(0xFFFCFCFC)
val appLightOnSurface = Color(0xFF1F1B16)
val appLightSurfaceVariant = Color(0xFFF0E0CF)
val appLightOnSurfaceVariant = Color(0xFF4F4539)
val appLightOutline = Color(0xFF817567)
val appLightInverseOnSurface = Color(0xFFF9EFE6)
val appLightInverseSurface = Color(0xFF34302A)
val appLightPrimaryInverse = Color(0xFFFFB945)

val appDarkPrimary = Color(0xFFFFB945)
val appDarkOnPrimary = Color(0xFF452B00)
val appDarkPrimaryContainer = Color(0xFF624000)
val appDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val appDarkSecondary = Color(0xFFDDC3A2)
val appDarkOnSecondary = Color(0xFF3E2E16)
val appDarkSecondaryContainer = Color(0xFF56442B)
val appDarkOnSecondaryContainer = Color(0xFFFADEBC)
val appDarkTertiary = Color(0xFFB8CEA2)
val appDarkOnTertiary = Color(0xFF243516)
val appDarkTertiaryContainer = Color(0xFF3A4C2B)
val appDarkOnTertiaryContainer = Color(0xFFD3EABC)
val appDarkError = Color(0xFFFFB4A9)
val appDarkErrorContainer = Color(0xFF930006)
val appDarkOnError = Color(0xFF680003)
val appDarkOnErrorContainer = Color(0xFFFFDAD4)
val appDarkBackground = Color(0xFF1F1B16)
val appDarkOnBackground = Color(0xFFEAE1D9)
val appDarkSurface = Color(0xFF1F1B16)
val appDarkOnSurface = Color(0xFFEAE1D9)
val appDarkSurfaceVariant = Color(0xFF4F4539)
val appDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val appDarkOutline = Color(0xFF9C8F80)
val appDarkInverseOnSurface = Color(0xFF32281A)
val appDarkInverseSurface = Color(0xFFEAE1D9)
val appDarkPrimaryInverse = Color(0xFF624000)
